
version: '3.8'

services:
  fastapi-backend:
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TEMP_DIR=/app/temp
      - MAX_WORKERS=2
      - LOG_LEVEL=info
      - ALLOWED_ORIGINS=http://frontend:3000,http://localhost:3000
    volumes:
      - ./python_backend:/app
      - temp-data:/app/temp
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - fastapi-backend
    restart: unless-stopped

volumes:
  temp-data:
