
version: '3.8'

services:
  fastapi-backend:
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TEMP_DIR=/app/temp
      - MAX_WORKERS=2
      - LOG_LEVEL=info
      - ALLOWED_ORIGINS=${RAILWAY_PUBLIC_DOMAIN:-*},${RAILWAY_STATIC_URL:-*}
    volumes:
      - temp-data:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - VITE_API_URL=${RAILWAY_SERVICE_FASTAPI_BACKEND_URL:-http://fastapi-backend:8000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      fastapi-backend:
        condition: service_healthy

volumes:
  temp-data:
