
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "serve -s dist -l 3000"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health.html"
healthcheckTimeout = 120
healthcheckInterval = 60
healthcheckStartPeriod = 60

[[services]]
name = "frontend"
dockerfile = "Dockerfile.frontend"
healthcheckPath = "/health.html"
healthcheckTimeout = 120
healthcheckInterval = 60
healthcheckStartPeriod = 60
routes = [
    { path = "/*", service = "frontend" }
]

[[services]]
name = "backend"
dockerfile = "python_backend/Dockerfile"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
healthcheckInterval = 60
healthcheckStartPeriod = 60
routes = [
    { path = "/api/*", service = "backend" }
]

[services.env]
PORT = "3000"
NODE_ENV = "production"
LOG_LEVEL = "info"
FASTAPI_URL = "${{RAILWAY_PUBLIC_DOMAIN}}/api"
