
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
dockerfile = "Dockerfile.frontend"
routes = [
    { path = "/*", service = "frontend" }
]

[[services]]
name = "backend"
dockerfile = "python_backend/Dockerfile"
routes = [
    { path = "/api/*", service = "backend" }
]

[services.env]
PORT = "3000"
