
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 120
healthcheckStartPeriod = 30

[[services]]
name = "frontend"
dockerfile = "Dockerfile.frontend"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckStartPeriod = 30
routes = [
    { path = "/*", service = "frontend" }
]

[[services]]
name = "backend"
dockerfile = "python_backend/Dockerfile"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
healthcheckStartPeriod = 30
routes = [
    { path = "/api/*", service = "backend" }
]

[services.env]
PORT = "3000"
NODE_ENV = "production"
LOG_LEVEL = "debug"
