
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyufmcbhvmdoupdnjtdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dWZtY2Jodm1kb3VwZG5qdGRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODY3MTksImV4cCI6MjA1OTQ2MjcxOX0.uDbY4JRvXFMdo1QzoRyAS1_Pk5UptTkCNc4QHRlMnUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
